### ISSUE TITLE
Kotlin stdlib conflict

### ISSUE THREAD

**Issue by ssuukk** [circlespainter/quasar-kotlin-gradle-template#2]
Trying to use this gradle config renders:

Error:A conflict was found between the following modules:
 - org.jetbrains.kotlin:kotlin-stdlib:1.0.0-beta-2423
 - org.jetbrains.kotlin:kotlin-stdlib:0.12.613

(although the later is never mentioned in config)

**Comment by circlespainter** [comment]
It is an old personal sample project, look into the kotlin branch of quasar-gradle-template instead.
